version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres-go-auth
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}       # From .env file
      POSTGRES_PASSWORD: ${DB_PASSWORD} # From .env file
      POSTGRES_DB: ${DB_NAME}         # From .env file
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  go-auth-service:
    image: go-auth-service:latest
    container_name: go_auth_service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      DATABASE_URL: postgres://${DB_USER}:${DB_PASSWORD}@postgres:${DB_PORT}/${DB_NAME} # Consumes from .env file
      JWT_SECRET: ${JWT_SECRET}           # Consumes from .env file
      SERVER_PORT: ${SERVER_PORT}         # Consumes from .env file
      ADMIN_EMAIL: ${ADMIN_EMAIL}         # Consumes from .env file
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}   # Consumes from .env file
    depends_on:
      - postgres

volumes:
  postgres_data:
